# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f487d360465b182d48b90891c781497bcb824d8ce646951742b7a348a95545945a24529ad8ddcceb9ece5f8af7e31883feba4d88b71e954fc7648c1abbe38d8e

test:
  secret_key_base: 4e0f73a31e38cfb578071f91b6cfb3e5befd39800fd0f8d1e4ea925e7bc41536a7555e9e9f22f67decee386a5ca26bd515de61323964441901ce3c85df616581

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
